#!/usr/bin/env python3
"""chance_methods.py -- every way of defining "chance", side by side.

Colocalization is always reported against a chance level, and the field's chance is
INDEPENDENCE: if tagging and activity were unrelated, P(activity+|tagged+) would equal
P(activity+). That is what `overlap_above_chance` computes.

Independence is violated in real tissue by things that are not biology. Measured on
M3 Hipp2 (2026-07-31):

  * SHARED PIXELS -- the activity marker is measured on the nucleus, so a tagged
    measure that also covers the nucleus is partly the same photons. Coupling scales
    with pixel overlap: nuclear 2.23x, whole-cell 1.34x, ring-only 1.10x, all measured
    among tagged-NEGATIVE cells where no biology can exist.
  * SPATIAL STRUCTURE -- tagged cells sit in neighbourhoods already richer in activity
    (14.7% vs 11.4% region-wide).
  * OVER-DETECTION -- spurious double-negative objects inflate N and deflate the
    baseline, inflating the ratio.

So control regions land at 1.5-2x rather than 1.0, and the honest question is not "is
this above 1" but "how far above the FLOOR is it". This module computes the same
quantity five ways so the floor is visible and the conclusion can be shown not to
depend on which definition is chosen.

  naive         P(act+|tag+) / P(act+)                  the field standard
  local         .. / activity among the k nearest NOT-tagged cells   [local_chance.py]
  fitted        .. / a model fitted on tagged-negatives  [expected_overlap.py]
  anchor_floor  the SAME statistic with a pseudo-marker built by thresholding the
                ANCHOR channel. The anchor has no biological relation to marker
                co-expression, so its ratio IS the technical floor -- measured, not
                modelled. Requires the `anchor_mean` export column.
  rotation      an empirical null: rotate the tagged cells' POSITIONS as a rigid body
                about the section centroid, re-assign tagged status to the nearest real
                cells, recompute. Preserves tagged-cell clustering, tissue shape and
                local density exactly; breaks only the alignment between channels.
                Assumption-free, and yields a p-value. **WEAK HERE, USE WITH CARE**:
                rotation randomises only the ANGULAR coordinate, so any confound with
                RADIAL structure survives it -- and brain sections are laminar and
                roughly concentric. Verified on synthetic data (2026-08-01): a purely
                spatial confound inflating the naive ratio to 2.08x still reads 1.34x
                after rotation. Treat it as a partial correction and a p-value, never
                as a clean null. `local` handles what rotation cannot.

NOTHING HERE DECIDES ANYTHING. Five numbers are printed next to each other so the
operator can compare them against what the image shows (CLAUDE.md: SEEN outranks any
computed baseline).

Usage:
    python3 chance_methods.py --project "<dir>" --regions CA1,CA3,STR
    python3 chance_methods.py --project "<dir>" --regions CA1 --plot out.png
    python3 chance_methods.py --self-test
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np
import pandas as pd
from scipy.spatial import cKDTree

sys.path.insert(0, str(Path(__file__).resolve().parent))

import cockpit_regions as creg   # noqa: E402
import cockpit_animal as ca      # noqa: E402
import local_chance as lc        # noqa: E402
import expected_overlap as eo    # noqa: E402

DEFAULT_ROTATIONS = 200


# ---------------------------------------------------------------------------
def naive_ratio(d: pd.DataFrame) -> float:
    base = d["activity"].mean()
    return d[d["tagged"]]["activity"].mean() / base if base > 0 else np.nan


def anchor_floor_ratio(d: pd.DataFrame, frac: float | None = None) -> float:
    """The naive statistic computed with a PSEUDO-marker cut from the anchor channel.

    The anchor (DAPI) says nothing about whether a cell co-expresses two markers, so
    any ratio it produces is generated by brightness/focus/thickness/detection alone --
    i.e. the technical floor, measured on the very same cells. Matching the pseudo-
    marker's prevalence to the real tagged prevalence keeps the base rates comparable,
    since ratios of this form are prevalence-sensitive.
    """
    if "anchor_mean" not in d.columns:
        return np.nan
    a = pd.to_numeric(d["anchor_mean"], errors="coerce")
    ok = a.notna()
    if ok.sum() < 200:
        return np.nan
    frac = frac if frac is not None else float(d["tagged"].mean())
    if not 0 < frac < 1:
        return np.nan
    cut = a[ok].quantile(1 - frac)
    pseudo = ok & (a > cut)
    base = d["activity"].mean()
    if pseudo.sum() == 0 or base <= 0:
        return np.nan
    return d.loc[pseudo, "activity"].mean() / base


def rotation_null(d: pd.DataFrame, n_rot: int = DEFAULT_ROTATIONS,
                  rng: np.random.Generator | None = None) -> dict:
    """Empirical null from rigid rotation of the tagged point pattern.

    Per section: rotate the tagged cells' coordinates about the section centroid by a
    random angle, then hand tagged status to the nearest real cell for each rotated
    point (without replacement, nearest-first). Tagged-cell clustering, the tissue
    outline and local density all survive; only the correspondence with activity is
    destroyed. The observed statistic is then read against that distribution.
    """
    rng = rng or np.random.default_rng(0)
    obs = float(d[d["tagged"]]["activity"].mean())
    null = []
    sections = list(d.groupby("section"))
    for _ in range(n_rot):
        hits, tot = 0, 0
        for _s, sub in sections:
            xy = sub[["centroid_x_px", "centroid_y_px"]].values
            tag = sub["tagged"].values
            act = sub["activity"].values
            if tag.sum() == 0 or len(sub) < 10:
                continue
            c = xy.mean(axis=0)
            th = rng.uniform(0, 2 * np.pi)
            R = np.array([[np.cos(th), -np.sin(th)], [np.sin(th), np.cos(th)]])
            rot = (xy[tag] - c) @ R.T + c
            # Estimate the LOCAL activity rate at each rotated position from its m
            # nearest real cells. An earlier version snapped each rotated point to its
            # single nearest cell and de-duplicated; that biased the null, because a
            # dense rotated cluster collapsed onto few cells and points landing outside
            # the cloud all snapped to the boundary. Averaging a neighbourhood is the
            # quantity actually wanted -- "how active is this location" -- and needs no
            # de-duplication.
            m = min(25, len(sub) - 1)
            _, idx = cKDTree(xy).query(rot, k=m)
            idx = np.atleast_2d(idx)
            hits += act[idx].mean(axis=1).sum(); tot += len(rot)
        if tot:
            null.append(hits / tot)
    null = np.array(null, dtype=float)
    if null.size == 0:
        return {"ratio": np.nan, "p": np.nan, "null_mean": np.nan}
    p = float((null >= obs).sum() + 1) / (len(null) + 1)
    return {"ratio": obs / null.mean() if null.mean() > 0 else np.nan,
            "p": p, "null_mean": float(null.mean())}


def compare(project_dir: Path, regions: list[str] | None = None, k: int = 100,
            n_rot: int = DEFAULT_ROTATIONS, seed: int = 0) -> pd.DataFrame:
    config = creg.load_pipeline_config(Path(project_dir))
    roles = ca.resolve_roles(config)
    tagged_col = f"{roles.tagged}_bgsub"
    d = lc._flags(lc.load_percell(project_dir), roles.tagged, roles.activity)
    d[tagged_col] = pd.to_numeric(d[tagged_col], errors="coerce")
    d = d.dropna(subset=[tagged_col, "nucleus_area_um2"])
    d = eo.add_local_density(d)

    ontology = creg.load_ontology(Path(project_dir))
    present = set(d["region_label"].dropna().unique())
    rng = np.random.default_rng(seed)
    rows = []
    for region in (regions or ["__ALL__"]):
        sub = d if region == "__ALL__" else d[
            d["region_label"].isin(ontology.descendants_or_self(region) & present)]
        if len(sub) < 500 or sub["tagged"].sum() < 30:
            print(f"  NOTE: '{region}' skipped (cells={len(sub)}, tagged={int(sub['tagged'].sum())})")
            continue
        loc = lc.region_local_chance(sub, k=k, n_boot=200, rng=rng)
        fit = eo.fitted_expectation(sub, tagged_col)
        rot = rotation_null(sub, n_rot=n_rot, rng=rng)
        rows.append({
            "region": region, "n_cells": len(sub), "n_tagged": int(sub["tagged"].sum()),
            "naive": naive_ratio(sub),
            "local": loc["above_chance_local"],
            "fitted": fit["ratio"],
            "anchor_floor": anchor_floor_ratio(sub),
            "rotation": rot["ratio"], "rotation_p": rot["p"],
            "ci_lo": loc["ci_lo"], "ci_hi": loc["ci_hi"],
        })
    return pd.DataFrame(rows)


# ---------------------------------------------------------------------------
def plot(df: pd.DataFrame, out: Path, title: str = "") -> None:
    """Grouped bars: one cluster per region, one bar per chance definition."""
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    METHODS = [("naive", "#2a78d6", "naive (region-wide)"),
               ("local", "#eb6834", "local neighbourhood"),
               ("fitted", "#1baf7a", "fitted null"),
               ("rotation", "#eda100", "rotation null"),
               ("anchor_floor", "#6b6b6b", "anchor floor (technical)")]
    SURFACE, INK, MUTED, GRID = "#fcfcfb", "#0b0b0b", "#6b6b6b", "#e3e3e0"

    d = df.dropna(subset=["naive"]).copy().sort_values("naive", ascending=False)
    n_m = len(METHODS)
    fig, ax = plt.subplots(figsize=(max(8, 1.5 * len(d) + 3), 5.4), dpi=200)
    fig.patch.set_facecolor(SURFACE); ax.set_facecolor(SURFACE)
    x = np.arange(len(d)); w = 0.8 / n_m

    for i, (col, colour, label) in enumerate(METHODS):
        if col not in d.columns:
            continue
        vals = d[col].values
        pos = x + (i - (n_m - 1) / 2) * w
        ax.bar(pos, vals, width=w * 0.9, color=colour, edgecolor=SURFACE,
               linewidth=1.2, label=label, zorder=3)
        for p_, v in zip(pos, vals):
            if np.isfinite(v):
                ax.text(p_, v + 0.05, f"{v:.2f}", ha="center", va="bottom",
                        fontsize=7, color=MUTED, zorder=4, rotation=90)

    ax.axhline(1.0, color=MUTED, lw=1.4, ls="--", zorder=2)
    ax.text(-0.55, 1.0, "independence", fontsize=8, color=MUTED, va="bottom", ha="left")
    ax.set_xticks(x); ax.set_xticklabels(d["region"], fontsize=10, color=INK)
    ax.set_ylabel("above-chance overlap  (x)", fontsize=9.5, color=INK)
    ax.set_title(title or "The same overlap, five definitions of chance",
                 fontsize=12, color=INK, loc="left", pad=12)
    ax.yaxis.grid(True, color=GRID, lw=0.8, zorder=0); ax.set_axisbelow(True)
    for s in ("top", "right"):
        ax.spines[s].set_visible(False)
    for s in ("left", "bottom"):
        ax.spines[s].set_color(GRID)
    ax.tick_params(colors=MUTED, labelsize=9)
    ax.legend(frameon=False, fontsize=8.5, ncol=2, loc="upper right", labelcolor=INK)
    fig.tight_layout()
    out.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out, facecolor=fig.get_facecolor(), bbox_inches="tight")
    plt.close(fig)
    print(f"  wrote {out}")


def _self_test() -> None:
    print("Running --self-test (synthetic sections, no project needed)...")
    rng = np.random.default_rng(11)
    check = lambda c, m: print(f"  {'ok  ' if c else 'FAIL'}  {m}") or (c or sys.exit(1))

    def make(n, spatial, real, sec="s1"):
        """Activity concentrated in PATCHES; tagged cells drawn preferentially from the
        same patches. This is cluster co-location -- the confound a rotation null is
        built to break. (A smooth global gradient is NOT: rotating about the centroid
        averages over it, so the null lands exactly on the naive baseline. Use the local
        baseline for gradients; the two methods are complementary, see module docstring.)"""
        x = rng.uniform(0, 1000, n); y = rng.uniform(0, 1000, n)
        centres = rng.uniform(120, 880, size=(6, 2))
        d2 = np.min(((x[:, None] - centres[:, 0]) ** 2
                     + (y[:, None] - centres[:, 1]) ** 2), axis=1)
        inpatch = d2 < 110 ** 2
        p_act = np.where(inpatch, 0.08 + spatial, 0.08)
        act = rng.random(n) < p_act
        w = np.where(inpatch, 1.0 + 12.0 * bool(spatial), 1.0)
        ti = rng.choice(n, n // 12, replace=False, p=w / w.sum())
        tag = np.zeros(n, bool); tag[ti] = True
        if real:
            act[tag & (rng.random(n) < real)] = True
        return pd.DataFrame({"tagged": tag, "activity": act, "centroid_x_px": x,
                             "centroid_y_px": y, "section": sec,
                             "anchor_mean": rng.normal(500, 80, n)})

    # spatial confound, NO real effect -> naive inflated, rotation null ~1.0
    d = make(20000, spatial=0.30, real=0.0)
    nv = naive_ratio(d)
    rot = rotation_null(d, n_rot=60, rng=np.random.default_rng(2))
    check(nv > 1.25, f"naive inflated by spatial structure alone ({nv:.2f}x)")
    # Rotation only randomises the ANGULAR coordinate. Verified 2026-08-01: with the
    # activity patches sitting at similar radii, 95% of cells at r<150 are in a patch,
    # so a rotated tagged cell lands in a high-activity annulus and the confound
    # largely survives. It reduces the inflation, it does not remove it -- and brain
    # sections are laminar/concentric, so this limit is real here, not synthetic.
    check(rot["ratio"] < nv,
          f"rotation reduces the inflation ({nv:.2f}x -> {rot['ratio']:.2f}x) but does "
          f"NOT null it: radius is preserved, so radial/laminar confounds survive")

    # genuine effect -> rotation null detects it
    d2 = make(20000, spatial=0.30, real=0.5)
    rot2 = rotation_null(d2, n_rot=60, rng=np.random.default_rng(2))
    check(rot2["ratio"] > rot["ratio"],
          f"a genuine effect still raises it above the confound-only case "
          f"({rot['ratio']:.2f}x -> {rot2['ratio']:.2f}x)")
    check(rot2["p"] < 0.05, f"and is significant (p={rot2['p']:.3f})")

    # anchor floor: a pseudo-marker unrelated to activity must sit at ~1.0
    af = anchor_floor_ratio(d)
    check(abs(af - 1.0) < 0.20, f"anchor pseudo-marker floor ~1.0x when uncoupled ({af:.2f}x)")

    print("\nself-test PASSED: rotation PARTIALLY corrects a spatial confound (it "
          "randomises angle only, so radial/laminar structure survives -- a real limit "
          "for brain sections), still responds to a genuine effect with p<0.05, and the "
          "anchor pseudo-marker reads ~1.0x when it carries no coupling.")


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(formatter_class=argparse.RawDescriptionHelpFormatter,
                                epilog=__doc__)
    p.add_argument("--project", type=Path, default=None)
    p.add_argument("--regions", default=None)
    p.add_argument("--k", type=int, default=100)
    p.add_argument("--rotations", type=int, default=DEFAULT_ROTATIONS)
    p.add_argument("--seed", type=int, default=0)
    p.add_argument("--out", type=Path, default=None)
    p.add_argument("--plot", type=Path, default=None)
    p.add_argument("--title", default="")
    p.add_argument("--self-test", action="store_true")
    a = p.parse_args()
    if not a.self_test and a.project is None:
        p.error("--project is required unless --self-test is set")
    return a


def main() -> int:
    a = parse_args()
    if a.self_test:
        _self_test(); return 0
    regions = [r.strip() for r in a.regions.split(",")] if a.regions else None
    df = compare(a.project, regions, k=a.k, n_rot=a.rotations, seed=a.seed)
    if df.empty:
        print("nothing to report"); return 1
    show = df.copy()
    for c in ("naive", "local", "fitted", "anchor_floor", "rotation", "ci_lo", "ci_hi"):
        if c in show:
            show[c] = show[c].round(2)
    print(show.to_string(index=False))
    print("\n  anchor_floor is the technical floor MEASURED on these same cells.")
    print("  A region is interesting when it clears that floor, not when it clears 1.0.")
    if a.out:
        a.out.parent.mkdir(parents=True, exist_ok=True); df.to_csv(a.out, index=False)
        print(f"  wrote {a.out}")
    if a.plot:
        plot(df, a.plot, a.title)
    return 0


if __name__ == "__main__":
    sys.exit(main())
